# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 365ba9d31c1caf5ff5c039335b3d0d0f88b34ec66f461aa801a490f7f26770564b35774f2c9c18f758a467033a59aa3c026696e22dcb7f03a9ce5e741c0806e1

test:
  secret_key_base: 1deb4a11cb6f52cf90b88b14dc70281cd04427887d21997c861bfe241b2395fcdbf5d444485da8a6681de842971f10cdb7c24cdf2c6cc9f09050ebcec05745bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
